name: Spellcheck Action
on: push

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install german dictionary
        run: npm install @cspell/dict-de-de

      - uses: streetsidesoftware/cspell-action@v5
        with:
          check_dot_files: false
          files: content/**/*.{md,html}
          incremental_files_only: false
          inline: warning
          strict: false
